# Example Site settings

google_analytics: UA-NNNNNNNN-N

title: 'Octavio Arriaga'

header_pages:
  - index.html
  - about.md

footer: 'follow me on <a href="https://twitter.com/octavio_arriaga">twitter</a>'

style: light # dark (default) or light
listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
